Support reading wflow models with input and/or output directories in the toml
Deltares/hydromt_wflow pull request #140
Opened 2023-01-09 08:23 UTC by JoostBuitink

Last year, the option to specify a `dir_input` and or `dir_output` was added to Wflow.jl. However, these options were not know to hydromt_wflow, so reading the model would skip the input and/or output files when this is specified in the Wflow .toml file. These changes fix this, and also adds the `dir_output` to the default toml file to improve the user experience of Wflow.

2023-01-09 09:17 UTC, hboisgon requested changes
Nice additions @JoostBuitink , thanks a lot!
I think really nice to change the default dir_output options as well: this however means that the built models will contain the change so good to check if the examples need to be updated and document the change in the changelog.

I also have a suggestion on how to insert dir_input and dir_output and suggest to apply the abs_path argument of get_config for them instead of the filename directly, might make it more robust.

2023-01-09 09:19 UTC, hboisgon commented
Hi @JoostBuitink 
Thanks for the changes! I left a small suggestion with the review :)

I see the tests are failing on glaciers though... not sure why... could you check it or do you prefer if I do?

2023-01-09 10:52 UTC, JoostBuitink commented on hydromt_wflow/wflow.py
> +        if "dir_input" in self.config.keys():
Good suggestion, thanks! I have implemented this now (also for all other checks for `dir_input` and `dir_output`)

2023-01-09 10:53 UTC, JoostBuitink commented
Hi @hboisgon! Thanks for the quick review! I have included your changes, and am currently looking in to the failing glacier test. Will let you know if I need some help with that!

2023-01-10 12:44 UTC, JoostBuitink commented
The failing test with the glaciers appears to be unrelated to this PR, as it also happend in another PR. I have created https://github.com/Deltares/hydromt_wflow/issues/143 to cover this problem

2023-03-14 02:20 UTC, hboisgon approved these changes

2023-03-14 02:43 UTC, merged