Implement NoDataStrategy to deal with optional setup_functions
Deltares/hydromt_wflow pull request #229
Opened 2024-01-11 16:09 UTC by JoostBuitink

## Issue addressed
Fixes #208, but needs https://github.com/Deltares/hydromt/issues/731 to be fixed in order to work.

## Explanation
Implemented a NoDataStrategy that ignores errors for the optional setup function (lakes, reservoirs, glacier and gauges). Now a warning is returned (in stead of an error), similar to the old behavior of hydromt_wflow. However, as the NoDataStrategy is currently incomplete in HydroMT-core, we need https://github.com/Deltares/hydromt/issues/731 to be fixed before this fix works.

## Checklist
- [ ] Updated tests or added new tests
- [ ] Branch is up to date with `main`
- [ ] Tests & pre-commit hooks pass
- [ ] Updated documentation if needed

2024-02-08 17:10 UTC, JoostBuitink commented
Stable tests are failing, because I believe that they do no yet use the latest version of hydromt (v0.9.3).

2024-02-09 15:45 UTC, dalmijn requested changes
Thanks for the good work! LGTM. I'd only request that `setup_reservoirs` is structured the same in this regard as the other methods.

2024-02-09 15:45 UTC, dalmijn commented on hydromt_wflow/wflow.py
> +            self.logger.info("Skipping method, as no data has been found")
I'd say, for consistency's sake, make this the same as the other methods, i.e.:
```Python
if ... is None:
    logger.warning(< warning message >)
    return
```

2024-02-11 06:37 UTC, Starphire1 commented
I'm excited about a new release. It would be great to have water level management and inflow/outflow calculations for lakes/reservoirs (if possible). It would also be nice if the created toml file at model build stage includes, e.g. lake = "wflow_lakelocs" and reservoir = "wflow_reservoirlocs" to reduce a manual model build step. The reservoir model build has been an exciting new addition to the model. Thanks for all the updates!

2024-02-13 12:15 UTC, dalmijn approved these changes
LGTM.

2024-02-13 12:16 UTC, merged