Bugfix 1dconnect
Deltares/hydromt_wflow pull request #269
Opened 2024-04-29 04:23 UTC by hboisgon

## Issue addressed
Fixes #251

## Explanation
There were several issues with the method.

- Bugfixes to connect to a river: subcatch did not always have unique ids + unwanted behavior if the area_max threshold is less than the wflow river upa threshold (tributaries gauges would then not end up on the river)

## Checklist
- [ ] Updated tests or added new tests
- [ ] Branch is up to date with `main`
- [ ] Tests & pre-commit hooks pass
- [ ] Updated documentation if needed

## Additional Notes (optional)
Add any additional notes or information that may be helpful.

2024-05-17 17:19 UTC, shartgring commented
Hi @hboisgon ! As a heads up, I was reviewing the code today, I expect to have the review finished next week. I was testing the method with the Vechte basin and noticed a few things which are worth mentioning/asking. 

When the provided geometry lies outside of the model domain, the error `ValueError("Coordinates outside domain.")` gets raised. Maybe this can be prevented by clipping the gdf to the bounds of the model in the workflow? Or checking the bounds of the gdf to the model bounds, and clipping when necessary?

![image](https://github.com/Deltares/hydromt_wflow/assets/103518935/34034b06-ad80-4b45-9dac-540977bfdadf)

Also related to clipping (as I had to clip my gdf's to get them working), using the `WflowModel.bounds` to clip results in incorrect behaviour when using include_river_boundaries=True. The entire model domain gets in `subcatch_1dmodel`I think this is caused by the bounds depending on the high-res basin and not the basin at model resolution? Using `WflowModel.grid.raster.bounds` did result in correct behaviour. Clipping the gdf by `WflowModel.grid.raster.bounds` might therefore prevent such behaviour?

![image](https://github.com/Deltares/hydromt_wflow/assets/103518935/f22cd604-bb57-4b76-87c7-73f90ef116c2)

When `area_max` is very large (1e6), we would not expect any point inflows right? As all cells will contribute to the 1d_model through `subcatch_1dmodel` as all upstream areas are smaller than `area_max`.  That is also confirmed by the log. Still, I get some tributary inflows when using such a large value (such as the green dot below). Is that expected behaviour?

![image](https://github.com/Deltares/hydromt_wflow/assets/103518935/ba5faf37-102a-46eb-9a9a-0777cf9ea687)

I also compared the difference between a gdf without small tributaries, and one with small tributaries (using `include_river_boundaries=False` to prevent that they get turned into point inflows). The differences are quite larger, especially for a large area_max. Shouldn't the total area of the `subcatch_1dmodel` be similar in those cases?

![image](https://github.com/Deltares/hydromt_wflow/assets/103518935/576d7907-ad2d-49fc-8ee6-7c3e01a72fc5)


The Santa Cruz case works indeed nicely with the changes when using a single geodataframe!
![image](https://github.com/Deltares/hydromt_wflow/assets/103518935/85e6e819-a71c-4b18-95c5-63074c31aa55)

In the images, the white dotted line is the river gdf, the blue features are the `subcatch_1dmodel`, red are `riv_1dmodel` and green dots are `gauges_1dmodel`

2024-05-22 09:22 UTC, shartgring requested changes
Nice work Hélène! I did some tests (see also the comments in the PR) and provided a suggestion to include clipping of the rivers, as I did encounter some problems with it in my case. There might be a better way to include the clipping, so I look forward to your thoughts on this

2024-05-24 03:48 UTC, hboisgon commented on hydromt_wflow/workflows/connect.py
>          # get the edges of the riv1d
Good catch! And no HydroMT uses a predicate to select index: https://github.com/Deltares/hydromt/blob/ad2548e43f30b84488e55a4afe3414a0d1f7a87d/hydromt/io.py#L561 so maybe we can update the docstrings but no exact clipping is done.
In main now, the self.basins property will now point to the "low-res" or actual wflow basins so this should get better. For now I used your fix but I could also have decide to add self.basins as an extra argument of the function.

2024-05-24 03:55 UTC, hboisgon commented
Thanks for the review @shartgring ! I fixed the clipping of the river. Could you send me your example model so that I can check what is going wrong if you use a large area max?

2024-05-30 07:11 UTC, shartgring commented
[testmodel_vecht.zip](https://github.com/Deltares/hydromt_wflow/files/15495077/testmodel_vecht.zip)
@hboisgon here it is!

2024-05-30 07:14 UTC, shartgring approved these changes
Looks good! Let me know if any changes are added when you have addressed the example model. Looking forward to your comments on that

2024-06-04 12:39 UTC, hboisgon commented
I looked partly at the Vecht and some things I notice is that the river shapefile contains very small inlet for tributaries (see picture) and these are not long enough to be snapped to the right wflow river (without upstream area propertyor a higher res wflow model). Because it's more a snapping issue, I don't think I want to solve it in hydromt-wflow, it's too complex and it's because of wrong snapping (so maybe impossible).

If you remove these small rivers, then things work nicely again apart for the most downstream part of the wflow basin for which no subbasin is built. Maybe this I can still improve in this PR but for the rest, I think it looks good for now for a first version.
![image](https://github.com/Deltares/hydromt_wflow/assets/45457510/6f1d4cfc-c9c9-45d6-b9c7-061c66a82d05)

2024-06-05 07:16 UTC, merged